import = [ "~/.config/alacritty/themes/alacritty_kanagawa_dragon.toml" ]

[font]
size = 14.0

[font.bold]
family = "Iosevka Nerd Font"
style = "bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Light Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "pl_PL.UTF-8"

[window]
decorations = "Full"
padding = { x = 15, y = 0 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[bell]
animation = "Linear"

[keyboard]
bindings = [
{ key = "V", mods = "Control|Shift", action = "ToggleViMode" },
]

[colors]
draw_bold_text_with_bright_colors = true

# [[hints.enabled]]
# hyperlinks = true
